name: deploy-frontend

on:
  push:
    branches: ["master"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo '🚀 Construyendo imagen Frontend...'

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/frontend-restapi:latest .

      - name: Show Docker images
        run: docker images

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/frontend-restapi:latest
